name: somos_qr_plus
description: SOMOS QR+ Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
flutter_launcher_icons:
  android: true
  ios: true
  image_path: ./assets/images/SOMOS_QRplus.png

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  go_router: ^13.0.0
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  get: ^4.7.2
  flutter_launcher_icons: ^0.14.4
  fl_chart: 0.66.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/somosqr-logo.png 